In [2]:
#Q1 - Import the numpy package under the name np
import numpy as np

In [10]:
#Q2 - Create a null vector of size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
#Q3 - Create a vector with values ranging from 10 to 49
Q3 = np.arange(10,50)  
Q3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
#Q4 - Find the shape of previous array in question 3
Q3.shape   

(40,)

In [17]:
#Q5 - Print the type of the previous array in question 3
Q3.dtype  

dtype('int32')

In [4]:
# Q6 - Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mirfa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/mirfa/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mirfa/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

In [23]:
# Q7 - Print the dimension of the array in question 3
Q3.ndim 

1

In [31]:
# Q8 - Create a boolean array with all the True values
np.ones(10, dtype=bool) 

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [32]:
# Q9 - Create a two dimensional array
np.ones((2,2)) 

array([[1., 1.],
       [1., 1.]])

In [33]:
# Q10 - Create a three dimensional array
np.ones((2,3,5)) 

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [8]:
# Q11 - Reverse a vector (first element becomes last)
Q11 = np.array([25,3,7,1,20,9]) 
Q11[::-1]

array([ 9, 20,  1,  7,  3, 25])

In [45]:
# Q12 - Create a null vector of size 10 but the fifth value which is 1
Q12 = np.zeros(10) 
Q12[4] = 1
Q12

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [53]:
# Q13 - Create a 3x3 identity matrix
np.identity(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
# Q14 - Convert the data type of the given array from int to float
arr = np.array([1, 2, 3, 4, 5]) 
#arr.dtype
arr = arr.astype('float64')
arr.dtype

dtype('float64')

In [62]:
# Q15 - Multiply arr1 with arr2
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [63]:
# Q16 - Make an array by comparing both the arrays provided above
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True]])

In [64]:
# Q17 - Extract all odd numbers from arr with values(0-9)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])  
arr[::2]

array([1, 3, 5, 7, 9])

In [70]:
# Q18 - Replace all odd numbers to -1 from previous array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])  
np.where(arr%2>0, -1, arr)

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [80]:
# Q19 - Replace the values of indexes 5,6,7 and 8 to 12
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [86]:
# Q20 - Create a 2d array with 1 on the border and 0 inside
Q20 = np.ones((3,4))
Q20[1:-1,1:-1] = 0
Q20

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [88]:
# Q21 - Replace the value 5 to 12
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [89]:
# Q22 - Convert all the values of 1st array to 64
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,:,:] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [90]:
# Q23 - Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
Q23 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Q23[0,:]

array([1, 2, 3])

In [92]:
# Q24 - Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
Q24 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Q24[1,:]

array([4, 5, 6])

In [93]:
# Q25 - Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
Q25 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Q25[2,:]

array([7, 8, 9])

In [12]:
# Q26 - Create a 10x10 array with random values and find the minimum and maximum values
Q26 = np.random.randn(10,10)
print(np.amax(Q26))
print(np.amin(Q26))

2.2332708137448996
-2.386697744379377


In [103]:
# Q27 - Find the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a==b]

array([2, 2, 4, 4])

In [114]:
# Q28 - Find the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(np.in1d(a,b))[0]

array([1, 3, 5, 7], dtype=int64)

In [24]:
# Q29 - Find all the values from array data where the values from array names are not equal to Will
Q29names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
Q29data = np.random.randn(7, 4)
#Q29data = np.arange(11,20)
Q29names_result = np.where(Q29names != 'Will')
#print(Q29names)
#print(Q29data)
#print(Q29names_result)
print(Q29data[Q29names_result])

[[-0.12050664 -0.57882578  0.42386759 -0.38733136]
 [-0.85686815  0.81531389 -0.16581602  2.64535345]
 [-0.69734581 -1.26330116  1.63921233 -1.24014464]
 [-0.2034536  -1.00754753  0.06540956  1.28644574]
 [ 0.68374332  0.8262448   1.75433632  0.21456398]]


In [31]:
# Q30 - Find all the values from array data where the values from array names are not equal to Will and Joe
Q30names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
Q30data = np.random.randn(7, 4)
#Q30data = np.arange(11,20)
Q30names_result = np.where((Q30names != 'Will') & (Q30names != 'Joe'))
#print(Q30names)
#print(Q30data)
#print(Q30names_result)
print(Q30data[Q30names_result])

[[ 0.37581479 -0.22598417 -1.45469387 -0.14453466]
 [ 0.79059361  1.13151397 -0.897094    0.63271186]]


In [42]:
# Q31 - Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.
Q31 = np.arange(1,16).reshape(5,3)
Q31

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [43]:
# Q32 - Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
Q32 = np.arange(1,17).reshape(2,2,4)
Q32

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [45]:
# Q33 - Swap axes of the array you created in Question 32
np.swapaxes(Q32,2,1)

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

In [46]:
# Q34 - Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0
Q34 = np.random.rand(10)
Res_Q34 = np.sqrt(Q34)
np.where(Res_Q34 < 0.5, 0 , Res_Q34)

array([0.        , 0.86464451, 0.75985704, 0.87969482, 0.        ,
       0.7382848 , 0.        , 0.        , 0.65724597, 0.76957771])

In [172]:
# Q35 - Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays
a = np.random.rand(12)
b = np.random.rand(12)
np.maximum.reduce([a,b])

array([0.98650144, 0.19534463, 0.81464201, 0.81028553, 0.65227079,
       0.91473434, 0.05982164, 0.96499664, 0.57097522, 0.89233328,
       0.82570583, 0.65941728])

In [47]:
# Q36 - Find the unique names and sort them out!
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [48]:
# Q37 - From array a remove all items present in array b
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [49]:
# Q38 - Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[2,:] = newColumn
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [10, 10, 10]])

In [224]:
# Q39 - Find the dot product of the above two matrix
Q39x = np.array([[1., 2., 3.], [4., 5., 6.]])
Q39y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(Q39x,Q39y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [221]:
# Q40 - Generate a matrix of 20 random values and find its cumulative sum
x = np.random.rand(20)
np.cumsum(x)

array([0.19065633, 0.82487061, 1.76342354, 2.02160993, 2.31409039,
       2.7397344 , 3.310913  , 4.30096856, 4.88916817, 5.77706756,
       6.43327884, 6.90605772, 7.21160625, 7.56178583, 8.33892012,
       8.51642917, 8.65436452, 8.86740949, 9.53632293, 9.90772788])