In [2]:
import numpy as np

In [3]:
#Question:1
#Convert a 1D array to a 2D array with 2 rows?
#Desired Output: array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
Q1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Q1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
#Question:2
#How to stack two arrays vertically?
#Desired Output: array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
Q2x = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
Q2y = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
np.concatenate((Q2x, Q2y), axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
#Question:3
#How to stack two arrays horizontally?
#Desired Output: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
Q3x = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
Q3y = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
np.concatenate((Q3x, Q3y), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [31]:
#Question:4
#How to convert an array of arrays into a flat 1d array?
#Desired Output::array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Q4x = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
np.ndarray.flatten(Q4x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
#Question:5
#How to Convert higher dimension into one dimension?
#Desired Output::array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
Q5x = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
Q5new_arr = Q5x.reshape(15)
Q5new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
#Question:6
#Convert one dimension to higher dimension?
#Desired Output::array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])
Q6x = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
Q6new_arr = Q5x.reshape(5,3)
Q6new_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [47]:
#Question:7
#Create 5x5 an array and find the square of an array?
Q7x = np.random.rand(5,5)
np.square(Q7x)

array([[9.31808611e-02, 1.21198802e-02, 3.62019035e-01, 3.23890264e-01,
        3.47238451e-01],
       [1.86283933e-02, 1.17695934e-01, 3.35142910e-01, 4.68432347e-01,
        9.80899167e-01],
       [9.00627169e-01, 9.68324161e-02, 2.14711456e-01, 2.51406958e-02,
        1.82013825e-01],
       [7.29778817e-02, 6.92133693e-01, 4.32512543e-02, 3.43498089e-01,
        9.48214739e-01],
       [4.69194705e-03, 4.79346960e-01, 3.00862080e-01, 8.12674066e-01,
        2.94052896e-04]])

In [50]:
#Question:8
#Create 5x6 an array and find the mean?
Q8x = np.random.rand(5,5)
np.mean(Q8x)

0.5730152710673105

In [51]:
#Question:9
#Find the standard deviation of the previous array in Q8?
np.std(Q8x)

0.2776704093377097

In [52]:
#Question:10
#Find the median of the previous array in Q8?
np.median(Q8x)

0.5454063854937587

In [53]:
#Question:11
#Find the transpose of the previous array in Q8?
np.transpose(Q8x)

array([[0.9152421 , 0.73983954, 0.38684953, 0.94070528, 0.54540639],
       [0.05599119, 0.99339762, 0.37890545, 0.28489268, 0.67564992],
       [0.15035753, 0.47668798, 0.90901394, 0.46345035, 0.67816714],
       [0.66142905, 0.85235113, 0.41094962, 0.39579345, 0.93124041],
       [0.6654565 , 0.50527361, 0.10451976, 0.92337379, 0.28043782]])

In [59]:
#Question:12
#Create a 4x4 an array and find the sum of diagonal elements?
Q12x = np.random.rand(4,4)
np.sum(Q12x.diagonal())

2.0052884888673885

In [62]:
#Question:13
#Find the determinant of the previous array in Q12?
np.linalg.det(Q12x)

-0.06019107480220062

In [1]:
#Question:14
#Find the 5th and 95th percentile of an array?
print(np.percentile(Q12x, 5))
print(np.percentile(Q12x, 95))

NameError: name 'np' is not defined

In [66]:
#Question:15
#How to find if a given array has any null values?
Q15x = np.arange(4).reshape(2,2)
np.isnan(Q15x)

array([[False, False],
       [False, False]])